### ISSUE TITLE
Asana API for sections isn't supported

### ISSUE THREAD

**Issue by dnesteryuk** [Asana/ruby-asana#15]
The current version of gem doesn't provide an ability to fetch sections of projects 

https://asana.com/developers/api-reference/projects#sections

**Comment by noonhub** [comment]
We can definitely add a feature request for a method on the project resource to retrieve the sections within a given project. However, keep in mind that you can make any arbitrary call to the API using the client. For instance `sections = $client.get("/projects/#{project-id}/sections")` will get you the sections

**Comment by noonhub** [comment]
This should be fixed in https://github.com/Asana/ruby-asana/commit/03a6250a63d1366d5d85985d7cd8fa89a86ad493
