### ISSUE TITLE
typo in request logging raises error

### ISSUE THREAD

**Issue by thimios** [Asana/ruby-asana#162]
There is a typo in `http_client.rb` that results in:

```
/home/thimios/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/asana-2.0.2/lib/asana/http_client.rb:178:in `format': key<bodt> not found (KeyError)
Did you mean?  :body
irb(main):003:0>
```
When there is a warning from asana.

I have created a PR to fix this typo:

https://github.com/Asana/ruby-asana/pull/161

Could someone please review it? @aw-asana @jv-asana

**Comment by jv-asana** [comment]
Hi @thimios, good catch. Thank you for sending in a PR to fix. We have gone ahead and merged your PR. It has also been deployed to RubyGems.org.
