### ISSUE TITLE
how do I get a project

### ISSUE THREAD

**Issue by mypark** [Asana/ruby-asana#33]
Is there example code on how to get a project from the workspace?

this is giving me an argument error 2 for 1

```
  workspace = client.workspaces.find_by_id(someId)
  projects = client.projects.find_by_workspace(workspace)
```

**Comment by noonhub** [comment]
Yes, in the examples directory, [personal_access_token.rb](https://github.com/Asana/ruby-asana/blob/master/examples/personal_access_token.rb) demonstrates using `find_by_workspace()` on the `tags` object which behaves just as it does on the `projects` object. 

The method requires just the ID of the workspace not a full workspace object as you are passing above.

**Comment by mypark** [comment]
just tried it with

projects = client.projects.find_by_workspace(workspace:00000000001234) 
#note that workspace id replaced with fake id for sample

and got the error 

```
Library/Ruby/Gems/2.0.0/gems/asana-0.3.0/lib/asana/resource_includes/resource.rb:40:in `method_missing': undefined method `projects' for #<Asana::Resources::Workspace:0x007f9742430130> (NoMethodError)
```
