### ISSUE TITLE
Runtime warning: already initialized constant Asana::Errors::InvalidRequest

### ISSUE THREAD

**Issue by reustmd** [Asana/ruby-asana#50]
I have a few applications that use the asana gem and all show me this warning when starting up.

![image](https://cloud.githubusercontent.com/assets/986962/22073899/99d1b5a4-dd74-11e6-9261-7ccc0c47162c.png)

**Comment by jjschnei** [comment]
It looks like there is something weird happening in your environment. Take a look at your paths. It appears that the Asana Ruby gem is being included from two places.
