### ISSUE TITLE
Portfolios support

### ISSUE THREAD

**Issue by aandis** [Asana/ruby-asana#64]
Does the lib not support [portfolios](https://asana.com/developers/api-reference/portfolios#) yet? Any expected ETA?

**Comment by praecipula** [comment]
Hey @aandis,

You're right - our client libraries don't yet have portfolios in them. We're aware of this and will work on it soon - expect our libraries to be up to date with our API features in the next month or two!

**Comment by rossgrambo** [comment]
You can use the lastest gem for portfolios!
