### ISSUE TITLE
Add Members to Project

### ISSUE THREAD

**Issue by bricemaurin** [Asana/ruby-asana#76]
Hi, this gem's documentation lack details. I'm trying to read the source code / the asana api documentation to understand the methods available..sorry if i miss something.

How can i add a member to a project ?

Thanks.
Brice

**Comment by rossgrambo** [comment]
You'll be hitting the https://asana.com/developers/api-reference/projects#members endpoint. In ruby it's on the Project class.

```
p = client.projects.find_by_id "64321946387"
p = p.add_members ['65163261','632173734','86539253']
```

The client libraries are pretty much just a reflection of the api docs. So wherever the endpoint is on there, it will be in the same place within the client library.

**Comment by bricemaurin** [comment]
thanks !
