### ISSUE TITLE
find a tag by its name

### ISSUE THREAD

**Issue by bricemaurin** [Asana/ruby-asana#77]
Hi
I'm trying to add tags to tasks I create. To do so I first query the existing tags to verify if it already exist / not, and if it doesn't, I create it.

```ruby
def find_or_create_tag(tag_name)
  tag_object = @client.tags.find_by_workspace(workspace: workspace.gid).select do |tag|
    tag.name == tag_name
  end.first

  if tag_object.nil?
    tag_object = create_tag(tag_name)
  end

  return tag_object
end

def create_tag(tag_name)
  @client.tags.create(
    workspace: workspace.gid,
    name: tag_name
    )
end
```
Unfortunately, it seems that the ```tags.find_by_workspace``` function doesn't return the full array of tags, so my ```find_or_create_tag``` function doesn't work.

How would you achieve this goal ?

Thanks !

**Comment by rossgrambo** [comment]
Hey @bricemaurin,

If you want to use that endpoint, you'd have to use [pagination](https://github.com/Asana/ruby-asana#pagination).

I'd recommend using [typeahead](https://github.com/Asana/ruby-asana/blob/4c13be3a864655b693913c2985e323b875fb8ec6/lib/asana/resources/workspace.rb#L97) and checking for resource type == tag. See our [docs](https://asana.com/developers/api-reference/typeaheads)

Feel free to reopen if these don't work for you!

**Comment by bricemaurin** [comment]
great. typeahead is waaayyy better. thanks @rossgrambo
