### ISSUE TITLE
search_in_workspace for tasks appears to be incomplete

### ISSUE THREAD

**Issue by rocco-haro** [Asana/ruby-asana#78]
In the php version, params is in the method signature: https://github.com/Asana/php-asana/blob/master/src/Asana/Resources/Gen/TasksBase.php#L203

Yet it is missing here https://github.com/Asana/ruby-asana/blob/master/lib/asana/resources/task.rb#L233 , rendering it useless other than for searching by resource subtype.

I was considering just settling for `find_all`, but it restricts to filtering by modified_since, when what we need is modified_at.after.

**Comment by rossgrambo** [comment]
Thanks @rocco-haro, 

You're totally right. I don't think that endpoint is even usable in its current state. I'll review the pr tomorrow. Even though it's only two lines, I want to ensure there's no weird behavior before merging.

Thank you again for making a PR!

**Comment by rocco-haro** [comment]
@rossgrambo Thank you for getting back to me so quickly! 

Looking forward to the change. 

Kind regards.

**Comment by rossgrambo** [comment]
You can use 0.9.3 which will have this fix. Thanks again!
