### ISSUE TITLE
task#search_in_workspace : Sections.any failure

### ISSUE THREAD

**Issue by rocco-haro** [Asana/ruby-asana#80]
Say I want to search for a task by modified date. 

I do the following:
```
w = AsanaClient.workspaces.find_all.first
t1 = Time.now - 4.days
t2 = Time.now - 2.days
t1 = t1.iso8601
t2 = t2.iso8601
options = {  fields: ['created_at', 'modified_at', 'completed_at', 'category', 'tags'], params: { 'modified_at.after': t1 ,  'modified_at.before': t2  } } 
 AsanaClient.tasks.search_in_workspace({workspace: w.id, options: options})
```
Works well and produces the url:
```
GET http://app.asana.com:443/api/1.0/workspaces/<redacted_id>/tasks/search?limit=20&modified_at.after=2019-09-01T17%3A20%3A30-07%3A00&modified_at.before=2019-09-03T17%3A20%3A30-07%3A00&opt_fields=created_at%2Cmodified_at%2Ccompleted_at%2Ccategory%2Ctags&opt_params=%7B%3A%22modified_at.after%22%3D%3E%222019-09-01T17%3A20%3A30-07%3A00%22%2C+%3A%22modified_at.before%22%3D%3E%222019-09-03T17%3A20%3A30-07%3A00%22%7D
```

Now if I want to filter by sections, I modify options to be the following:
```
options = {  fields: ['created_at', 'modified_at', 'completed_at', 'category', 'tags'], params: { 'modified_at.after': t1 , 'sections.any': <redacted_id> , 'modified_at.before': t2  } } 
```
When I execute
```
 AsanaClient.tasks.search_in_workspace({workspace: w.id, options: options})
```
the following url
```
GET http://app.asana.com:443/api/1.0/workspaces/<redacted_id>/tasks/search?limit=20&modified_at.after=2019-09-01T17%3A20%3A30-07%3A00&modified_at.before=2019-09-03T17%3A20%3A30-07%3A00&opt_fields=created_at%2Cmodified_at%2Ccompleted_at%2Ccategory%2Ctags&opt_params=%7B%3A%22modified_at.after%22%3D%3E%222019-09-01T17%3A20%3A30-07%3A00%22%2C+%3A%22sections.any%22%3D%3E1135740032216942%2C+%3A%22modified_at.before%22%3D%3E%222019-09-03T17%3A20%3A30-07%3A00%22%7D&sections.any=<redacted_id>
```
I get an error claiming `"message":"sections.any: Not a recognized ID: <redacted_id>"`
 
Now I know that the error is incorrect because I am able to get a 200 response when I don't use the gem:

```
  def build_task_request(path)
    uri = URI.parse(@@base_url + path)
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    req = Net::HTTP::Get.new(uri.request_uri)
    req['Authorization'] = 'Bearer ' + '<redacted_token>'
    [http, req]
  end

    fields_of_interest = ['created_at', 'modified_at', 'completed_at', 'category', 'tags']
    time = Time.now - 1.year
    time = time.iso8601

    # by section 
    http, req = build_task_request('/workspaces/<redacted_id>/tasks/search?limit=100&sections.any=<redacted_id>&opt_fields='+fields_of_interest.join(',')+'&opt_params=%7B%3A%22modified_at.after%22%3D%3E%222019-09-01T15%3A40%3A12-07%3A00%22%2C+%3A%22modified_at.before%22%3D%3E%222019-09-03T15%3A40%3A12-07%3A00%22%2C+%3A%22sections.any%22%3D%3E1135740032216942%7D&sections.any=<redacted_id>')

    res = JSON(http.request(req).body)
    tasks = res['data']
```

produces the following url:

```
GET http://app.asana.com:443/api/1.0/workspaces/<redacted_id>/tasks/search?limit=100&sections.any=1135740032216942&opt_fields=created_at,modified_at,completed_at,category,tags&opt_params=%7B%3A%22modified_at.after%22%3D%3E%222019-09-01T15%3A40%3A12-07%3A00%22%2C+%3A%22modified_at.before%22%3D%3E%222019-09-03T15%3A40%3A12-07%3A00%22%2C+%3A%22sections.any%22%3D%3E1135740032216942%7D&sections.any=<redacted_id>
```
and a response with no errors, and a list of tasks. 

I've triple checked that I was clear of typos with respect to workspace and section ids. 

What i've noticed is that the URLs get built differently. Sections.any is not included along with modified_at.after or modified_at.before. I don't know if that's the issue or not, but I would appreciate some investigation into this. 

Kind regards.

**Comment by rossgrambo** [comment]
I can't get the gem to give me this error. Everything succeeds when I hit

```
options = {  fields: ['created_at', 'modified_at', 'completed_at', 'category', 'tags'], params: { 'modified_at.before' => "2019-09-06T14:48:00.000Z" , 'modified_at.after' => "2011-10-05T14:48:00.000Z", 'sections.any'=> "987654321" }}


t = client.tasks.search_in_workspace(workspace: "1234567890", options: options,)
```

And the produced urls you have work when testing with curl. 

1. Are you on the lastest gem. 0.9.3
2. Try to run these two lines with manually typing in your ids and iso strings:
```
options = {  fields: ['created_at', 'modified_at', 'completed_at', 'category', 'tags'], params: { 'modified_at.before' => "2019-09-06T14:48:00.000Z" , 'modified_at.after' => "2011-10-05T14:48:00.000Z", 'sections.any'=> "987654321" }}

t = client.tasks.search_in_workspace(workspace: "1234567890", options: options,)
```
3. If this still doesn't work could you debug walk through it and let me know which line is giving you this error?

**Comment by rocco-haro** [comment]
Hi @rossgrambo , thanks for the response. 

1. Yes I am;
2. I ran them, still the same error. 
3. It fails in the Faraday Connector, so that means the error is in the handling of the request? I'll just share the workspace_id: 42212990364678 & section_id: 1135740032216942. Please let me know when you've jotted them down so I can redact them from this post.

Kind regards.

**Comment by rossgrambo** [comment]
Even with your ids, I don't have access to your data, so unfortunately, I can't recreate your request.

It looks like that error occurs when the id your passing to sections.any is a section you don't have access to/incorrect.

This means your request is successfully making it to the server.

Could you run `client.sections.find_by_id` right before your search call on the given section to see if it gives you an error? 

You could use a proxy to watch the traffic and see exactly what value is being sent.

**Comment by rocco-haro** [comment]
This is an interesting issue: I ran client.sections.find_by_id and got the same error, which confirms there is an issue with the gem?

What I don't understand is why I **don't** get an error when I make the request to the search API using NET::HTTP. It works perfectly fine and I actually get results using the same section_id

**Comment by rossgrambo** [comment]
At this point I think the best approach is to setup a proxy, or some sort of traffic monitoring so we can see the difference between the requests from the gem and from NET::HTTP. 

Are we sure they're both using the same PAT or auth? 

You could run 
```
puts AsanaClient.instance_variable_get("@http_client").instance_variable_get("@authentication").instance_variable_get("@token")
```

To see what token the gem is using and compare that with whichever one you're using in NET::HTTP

**Comment by rocco-haro** [comment]
Yeah, so the tokens are identical. 

The urls differ:

NET:HTTP
```
http://app.asana.com:443/api/1.0/workspaces/42212990364678/tasks/search?limit=100&modified_at.after=2018-09-05T15:47:07-07:00&sections.any=1135740032216942&opt_fields=created_at,modified_at,completed_at,category,tags&opt_params=%7B%3A%22modified_at.after%22%3D%3E%222019-09-01T15%3A40%3A12-07%3A00%22%2C+%3A%22modified_at.before%22%3D%3E%222019-09-03T15%3A40%3A12-07%3A00%22%2C+%3A%22sections.any%22%3D%3E1135740032216942%7D&sections.any=1135740032216942
```

gem (notice how sections.any is not with the initial modified_at filters)
```
http://app.asana.com:443/api/1.0/workspaces/42212990364678/tasks/search?limit=20&modified_at.after=2019-09-01T15%3A48%3A06-07%3A00&modified_at.before=2019-09-03T15%3A48%3A06-07%3A00&opt_fields=created_at%2Cmodified_at%2Ccompleted_at%2Ccategory%2Ctags&opt_params=%7B%3A%22modified_at.after%22%3D%3E%222019-09-01T15%3A48%3A06-07%3A00%22%2C+%3A%22modified_at.before%22%3D%3E%222019-09-03T15%3A48%3A06-07%3A00%22%2C+%3A%22sections.any%22%3D%3E1135740032216942%7D&sections.any=1135740032216942
```

**Comment by rossgrambo** [comment]
But that's because you're passing it in like that to NET:HTTP

```
http, req = build_task_request('/workspaces/<redacted_id>/tasks/search?limit=100&sections.any=<redacted_id>&opt_fields='+fields_of_interest.join(',')+'&opt_params=%7B%3A%22modified_at.after%22%3D%3E%222019-09-01T15%3A40%3A12-07%3A00%22%2C+%3A%22modified_at.before%22%3D%3E%222019-09-03T15%3A40%3A12-07%3A00%22%2C+%3A%22sections.any%22%3D%3E1135740032216942%7D&sections.any=<redacted_id>')
```

Try removing the first occurance of the sections.any and see if NET:HTTP still succeeds.

**Comment by rossgrambo** [comment]
Even if it was the url that was the problem, if you run the gem produced url as a curl command it works.

```
curl -X GET "https://app.asana.com/api/1.0/workspaces/<redacted_id>/tasks/search?limit=20&modified_at.after=2018-09-01T15%3A48%3A06-07%3A00&modified_at.before=2019-09-06T15%3A48%3A06-07%3A00&opt_fields=created_at%2Cmodified_at%2Ccompleted_at%2Ccategory%2Ctags&opt_params=%7B%3A%22modified_at.after%22%3D%3E%222018-09-01T15%3A48%3A06-07%3A00%22%2C+%3A%22modified_at.before%22%3D%3E%222019-09-06T15%3A48%3A06-07%3A00%22%2C+%3A%22sections.any%22%3D%3E<redacted_id>%7D&sections.any=<redacted_id>"  -H 'Accept: application/json'  -H "Authorization: Bearer <redacted_pat>"
```

**Comment by rocco-haro** [comment]
Thanks for your help. 

This was my fault, when preparing the AsanaClient I had set headers
c.default_headers({ 'asana-enable' => 'new_sections' })
and without that header declaration it works fine. 

I appreciate your time.

**Comment by rossgrambo** [comment]
Oh nice! Glad you found the issue! 😄 I'm sure others will run into something similar, so it's nice to have this thread they can reference!
