### ISSUE TITLE
Unnecessary #get calls

### ISSUE THREAD

**Issue by rocco-haro** [Asana/ruby-asana#81]
Say I attempt to get tasks and pass opt_fields = { fields: [tag.name] }
``` 
1 - tasks = AsanaClient.tasks.by_project(project: 1, options: opts)
2 - tasks.each do |t|
3 -  tags = t.tags
4 - end
```

When the line 3 is executed, the client performs a #get to tasks/{id}/tags. Why is this done? The information for tags was already returned in line 1, and this #get call returns data: [] most of the time. As a result, our job spends time wasted making this call, and creates unnecessary load to the Asana API.

Is there a way to prevent certain calls from being made?

**Comment by rossgrambo** [comment]
Hey @rocco-haro,

Yeah, I'm not a fan of this part of these libraries. If you look at the repo's definition for [task](https://github.com/Asana/ruby-asana/blob/f02337260770bf0c438652b8894ecff9954d91cd/lib/asana/resources/task.rb#L421), you can see that 'tags' is defined as both an attr_reader and a function that gets tag data. I believe the intent was that it would casually grab the data as you asked for it.

However if you're opting fields correctly, it kind of just gets in the way. I'm hoping to refactor these at some point, but I can't think of a good way without breaking existing apps.

That being said, I think you can get around this by doing this:
```
tags = t.instance_variable_get("@tags");
```

Let me know if you have any suggestions on how to resolve this, as I'm confused why it was built like this in the first place... 😢

**Comment by rocco-haro** [comment]
Thanks for the quick response @rossgrambo. 

It is unfortunate, but your advice worked! 

I appreciate.
