### ISSUE TITLE
Task methods return 404

### ISSUE THREAD

**Issue by lkubie** [Asana/ruby-asana#83]
I can successfully return a Task using `client.tasks.find_by_id(my_task.gid)`. However I get a 404 when attempting to perform any action on the same Task. 

For example: 
`client.tasks.find_by_id(my_task.gid)` returns the task I would like to modify, but
`client.tasks.find_by_id(my_task.gid).delete()` and `client.tasks.find_by_id(my_task.gid).update({completed:true})`
return 404 errors. 

These called used to work, but stopped working sometime in the last ~1 month. Attached is a stack trace.

![asana_staketrace](https://user-images.githubusercontent.com/23003995/68137099-9e659700-fee3-11e9-9acc-8d7e21ec34ec.png)

**Comment by rossgrambo** [comment]
Sorry I'm quite late to respond here.

This occurred when our API replaced id with gid. Upgrading to the newest version of the client library should fix this.
