### ISSUE TITLE
Prevent duplication task

### ISSUE THREAD

**Issue by akshayBabar** [Asana/ruby-asana#84]
Hi, I am just using asana gem for task creation on asana when any test suit failed (i.e. job status failed) then I am able to create a task. I have a job which run the test on a daily basis and if the same test again gets failed then I don't want to create a new task but want to add a comment on the existing task if the old task is open and status is not completed. Right now if the same test gets failed then it's creating a new task.

How I am able to achieve this. 
Thanks!

**Comment by rossgrambo** [comment]
I apologize for being late to respond to this, but the answer is: It depends.

You could store information locally about the tasks you create. 
You could make a custom field with the ID of the test suit or some identifier, and ensure that it doesn't exist.
I think the best option is to store the ID of the test suite as external data on the task https://developers.asana.com/docs/#custom-external-data . That way you can post a comment to /tasks/{external_id} and if that fails, create a task.

Hope this helps you or others who find their way here!
