### ISSUE TITLE
Disable Multiple "Asana Change Warnings"

### ISSUE THREAD

**Issue by pensan** [Asana/ruby-asana#85]
We are trying to set up the client to not show warnings for "string_ids" and "new_sections".

What is the correct syntax to define multiple values for the "asana-enable" header?

Our current code:
```
Asana::Client.new do |c|

  c.default_headers "asana-enable" => "string_ids"

  c.authentication :access_token, 'XXXXX'

end
```

We tried already these without success:
`c.default_headers "asana-enable" => ["string_ids", "new_sections"]`
`c.default_headers "asana-enable" => "string_ids new_sections"`
`c.default_headers "asana-enable" => "string_ids, new_sections"`

and even (which, of course, does not work)
```
c.default_headers "asana-enable" => "string_ids"
c.default_headers "asana-enable" => "new_sections"
```

Is there a way to set multiple values?

**Comment by rossgrambo** [comment]
c.default_headers "asana-enable" => "string_ids,new_sections"

Above works for me, have you tried without the space in your string? Not sure if that's the difference.

**Comment by pensan** [comment]
This works, yes.

Thank you very much
