### ISSUE TITLE
Asana::Project does not have an `id` instance method

### ISSUE THREAD

**Issue by mferrier** [Asana/ruby-asana#91]
[The API](https://www.rubydoc.info/github/Asana/ruby-asana/master/Asana/Resources/Project) says Asana::Project has an instance method `id`, but in [the code](https://github.com/Asana/ruby-asana/blob/master/lib/asana/resources/project.rb#L19) it's `gid`.

gem version asana-0.10.1

**Comment by rossgrambo** [comment]
Rubydoc has been updated
