### ISSUE TITLE
Asana::Task does not have an `id` instance method

### ISSUE THREAD

**Issue by mferrier** [Asana/ruby-asana#92]
Similar to #91, [the docs](https://www.rubydoc.info/github/Asana/ruby-asana/master/Asana/Resources/Task#id-instance_method) say that Asana::Task has an `id` instance method, but in [the code](https://github.com/Asana/ruby-asana/blob/master/lib/asana/resources/task.rb#L16) it's `gid`.

gem version asana-0.10.1

**Comment by rossgrambo** [comment]
Took a while for rubydocs to catch up, but everything looks good now.
