### ISSUE TITLE
Searching workspace bugs/confusion

### ISSUE THREAD

**Issue by chrismo** [Asana/ruby-asana#93]
The code generation for the `search_tasks_for_workspace` method on `TasksBase` translates the periods in all of the parameters that have them into underscores, causing the wrong params to be emitted. 

So this call fails:
```
Asana::Resources::TasksBase.search_tasks_for_workspace(
  @asana_client,
  workspace_gid: @workspace_gid,
  followers_any: @asana_user_id
)
```

There is another place this endpoint is surfaced in the gem, in `Asana::Resources::Task.search_in_workspace`. This doesn't have first-class params for the search parameters, just a params and options hash (which to me seemed less helpful than the other method, which is why I tried it first). But it does allow for string-symbol keys that are accurate:

```
Asana::Resources::Task.search_in_workspace(
  @asana_client,
  workspace: @workspace_gid,
  options: {params: {"followers.any": @asana_user_id}
  }
)
```

I didn't see anything in the docs for this issue, so if I've overlooked something, happy to learn! :)

**Comment by rossgrambo** [comment]
Hey @chrismo ,

You're right, these params were not being generated correctly. If you upgrade to v0.10.2, they should now work as expected! 

Let me know if you have any issues!
