### ISSUE TITLE
Release later than 0.10.2? Attachment IO, please!

### ISSUE THREAD

**Issue by StefanRitchie** [Asana/ruby-asana#98]
Hi there,

I'm really keen to get the attachment IO code into the gem so I can retain the file's existing filename when uploading from a `form_with` `file_field`.

Alternatively, if there is currently a way to retain the original filename, I'd gladly implement that.

At the moment I'm using this code:
```ruby
unless @params[:files].count.zero?
  @params[:files].each do |file|
    task.attach(
      filename: file.tempfile.path,
      mime: file.content_type
    )
  end
end
```

But I'd like to do the following (which looks possible in 11f7f33):
```ruby
unless @params[:files].count.zero?
  @params[:files].each do |file|
    task.attach(
      io: file.to_io,
      filename: file.original_filename,
      mime: file.content_type
    )
  end
end
```

**Comment by rossgrambo** [comment]
0.10.3 was just released
